### ISSUE TITLE
Segfaults when run

### ISSUE THREAD

**Issue by duncan-bayne** [AugustoRuiz/Img2CPC#5]
```
➜  Img2CPC git:(master) mkdir obj
➜  Img2CPC git:(master) gmake -f Makefile.others 
g++ -std=c++11 -O3 -Werror -Wall -fsigned-char -o obj/Palette.o -c -Iinclude src/Palette.cc
g++ -std=c++11 -O3 -Werror -Wall -fsigned-char -o obj/TileExtractor.o -c -Iinclude src/TileExtractor.cc
g++ -std=c++11 -O3 -Werror -Wall -fsigned-char -o obj/img2cpc.o -c -Iinclude src/img2cpc.cc
g++ -std=c++11 -O3 -Werror -Wall -fsigned-char -o obj/jsoncpp.o -c -Iinclude src/jsoncpp.cpp
g++  -o bin/img2cpc obj/Palette.o obj/TileExtractor.o obj/img2cpc.o obj/jsoncpp.o -lfreeimage
➜  Img2CPC git:(master) ./bin/img2cpc --help
[1]    58442 segmentation fault (core dumped)  ./bin/img2cpc --help
```

I'll submit a PR for this shortly, as part of my work to get this tool working on FreeBSD.

**Comment by duncan-bayne** [comment]
Closing for now as haven't had any opportunity to get this going on FreeBSD.

**Comment by AugustoRuiz** [comment]
I don't have a FreeBSD to test this on. On Ubuntu, Mint, Debian and Arch is
working properly...

Could you try to modify the Makefile so that the compilation includes
symbols, (adding a -g switch), so we can see where is the problem? It's
weird it's crashing when showing the help messages... :(

Kind regards,



Augusto.
